export const BEGIN_LOAD_ALL_SEAT_TYPES = "BEGIN_LOAD_ALL_SEAT_TYPES";
export const LOAD_ALL_SEAT_TYPES_SUCCESS = "LOAD_ALL_SEAT_TYPES_SUCCESS";
export const TOGGLE_SEAT_TYPE_MODAL = "TOGGLE_SEAT_TYPE_MODAL";
export const HANDLE_SEAT_TYPE_MODAL = "HANDLE_SEAT_TYPE_MODAL";
export const BEGIN_SAVE_SEAT_TYPE = "BEGIN_SAVE_SEAT_TYPE";
export const EDIT_SEAT_TYPE_SUCCESS = "EDIT_SEAT_TYPE_SUCCESS";
export const EDIT_SEAT_TYPE_ERROR = "EDIT_SEAT_TYPE_ERROR";
