FROM quanca/laravel
COPY ./sync.sh /home/sync.sh
RUN chmod +x /home/sync.sh
RUN apt-get install git -y
RUN git config --global user.name "Quan"
RUN git config --global user.username "caoquan95"
RUN git config --global user.email "aquancva@gmail.com"
