export const TOGGLE_ADD_MESSAGE_MODAL = "TOGGLE_ADD_MESSAGE_MODAL";
export const TOGGLE_ADD_RECEIVER_MODAL = "TOGGLE_ADD_RECEIVER_MODAL";

export const BEGIN_LOAD_ALL_MESSAGE = "BEGIN_LOAD_ALL_MESSAGE";
export const LOAD_ALL_MESSAGE_SUCCESS = "LOAD_ALL_MESSAGE_SUCCESS";
export const LOAD_TEMPLATE_SUCCESS = "LOAD_TEMPLATE_SUCCESS";
export const UPLOAD_MESSAGE = "UPLOAD_MESSAGE";
export const BEGIN_SAVE_MESSAGE = "BEGIN_SAVE_MESSAGE";
export const SAVE_MESSAGE_SUCCESS = "SAVE_MESSAGE_SUCCESS";
export const EDIT_MESSAGE_SUCCESS = "EDIT_MESSAGE_SUCCESS";

export const BEGIN_LOAD_ALL_RECEIVER = "BEGIN_LOAD_ALL_RECEIVER";
export const LOAD_ALL_RECEIVER_SUCCESS = "LOAD_ALL_RECEIVER_SUCCESS";

export const BEGIN_LOAD_RECEIVERS_MODAL = "BEGIN_LOAD_RECEIVERS_MODAL";
export const LOAD_RECEIVERS_MODAL_SUCCESS = "LOAD_RECEIVERS_MODAL_SUCCESS";
export const LOAD_ALL_GENS = "LOAD_ALL_GENS";
export const LOAD_ALL_CLASSES = "LOAD_ALL_CLASSES";
export const TOGGLE_CHOOSE_RECEIVERS = "TOGGLE_CHOOSE_RECEIVERS";