export const SHOW_CREATE_REGISTER_MODAL = "SHOW_CREATE_REGISTER_MODAL";
export const BEGIN_CREATE_REGISTER = "BEGIN_CREATE_REGISTER";
export const CREATE_REGISTER_SUCCESS = "CREATE_REGISTER_SUCCESS";
export const UPDATE_CREATE_REGISTER_FORM_DATA = "UPDATE_CREATE_REGISTER_FORM_DATA";
export const BEGIN_LOAD_COURSES = "BEGIN_LOAD_COURSES";
export const LOADED_COURSES_SUCCESS = "LOADED_COURSES_SUCCESS";
export const LOADED_COURSES_ERROR = "LOADED_COURSES_ERROR";
export const BEGIN_LOAD_CLASSES = "BEGIN_LOAD_CLASSES";
export const LOADED_CLASSES_SUCCESS = "LOADED_CLASSES_SUCCESS";
export const LOADED_CLASSES_ERROR = "LOADED_CLASSES_ERROR";
export const SAVED_REGISTER_ERROR = "SAVED_REGISTER_ERROR";
export const BEGIN_SAVE_REGISTER = "BEGIN_SAVE_REGISTER";
export const SAVED_REGISTER_SUCCESS = "SAVED_REGISTER_SUCCESS";
export const BEGIN_LOAD_CAMPAIGNS = "BEGIN_LOAD_CAMPAIGNS";
export const LOADED_CAMPAIGNS_SUCCESS = "LOADED_CAMPAIGNS_SUCCESS";
export const LOADED_CAMPAIGNS_ERROR = "LOADED_CAMPAIGNS_ERROR";

