export const SHOW_CREATE_REGISTER_MODAL = "SHOW_CREATE_REGISTER_MODAL";
export const BEGIN_CREATE_REGISTER = "BEGIN_CREATE_REGISTER";
export const CREATE_REGISTER_SUCCESS = "CREATE_REGISTER_SUCCESS";
export const UPDATE_CREATE_REGISTER_FORM_DATA = "UPDATE_CREATE_REGISTER_FORM_DATA";
