export const LOAD_ALL_SESSIONS_SUCCESS = "LOAD_ALL_SESSIONS_SUCCESS";
export const LOAD_SHOWING_SESSION_SUCCESS = "LOAD_SHOWING_SESSION_SUCCESS";
export const LOAD_COMING_SESSION_SUCCESS = "LOAD_COMING_SESSION_SUCCESS";
export const LOAD_DAY_SESSION_SUCCESS = "LOAD_DAY_SESSION_SUCCESS";
export const TOGGLE_ADD_EDIT_SESSION_MODAL = "TOGGLE_ADD_EDIT_SESSION_MODAL";