export const LOAD_ALL_FILMS_SUCCESS = "LOAD_ALL_FILMS_SUCCESS";
export const LOAD_SHOWN_FILMS_SUCCESS = "LOAD_SHOWN_FILMS_SUCCESS";
export const BEGIN_LOAD_ALL_FILMS = "BEGIN_LOAD_ALL_FILMS";
export const SHOW_ADD_EDIT_FILM_MODAL = "SHOW_ADD_EDIT_FILM_MODAL";
export const DISPLAY_GLOBAL_LOADING = "DISPLAY_GLOBAL_LOADING";
export const HIDE_GLOBAL_LOADING = "HIDE_GLOBAL_LOADING";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const BEGIN_SAVE_FILM = "BEGIN_SAVE_FILM";
export const SAVE_FILM_SUCCESS = "SAVE_FILM_SUCCESS";
export const HANDLE_AVATAR_WEBSITE_TAB_FILM = "HANDLE_AVATAR_WEBSITE_TAB_FILM";
export const HANDLE_AVATAR_WEBSITE_TAB_FILM2 = "HANDLE_AVATAR_WEBSITE_TAB_FILM2";
export const HANDLE_FILM_MODAL = "HANDLE_FILM_MODAL";
export const EDIT_FILM_SUCCESS = "EDIT_FILM_SUCCESS";
export const EDIT_FILM_ERROR = "EDIT_FILM_ERROR";
export const EDIT_STATUS_SUCCESS = "EDIT_STATUS_SUCCESS";
export const EDIT_FAVORITE_SUCCESS = "EDIT_FAVORITE_SUCCESS";
export const LOAD_ALL_FILMS_HAVE_PAGINATION_SUCCESS = "LOAD_ALL_FILMS_HAVE_PAGINATION_SUCCESS";
export const HANDLE_IMAGES_WEBSITE_FILM = "HANDLE_IMAGES_WEBSITE_FILM";
export const SHOW_FILM_SESSION = "SHOW_FILM_SESSION";
export const CLEAR_TO_LOAD_PAGE = "CLEAR_TO_LOAD_PAGE";
export const ADD_FILM_SESSION_ON_TAB_FILM = "ADD_FILM_SESSION_ON_TAB_FILM";



export const BEGIN_LOAD_ALL_SESSIONS = "BEGIN_LOAD_ALL_SESSIONS";
export const LOAD_ALL_SESSIONS_SUCCESS = "LOAD_ALL_SESSIONS_SUCCESS";
export const BEGIN_LOAD_SHOWING_SESSION = "BEGIN_LOAD_SHOWING_SESSION";
export const LOAD_SHOWING_SESSION_SUCCESS = "LOAD_SHOWING_SESSION_SUCCESS";
export const TOGGLE_ADD_EDIT_SESSION_MODAL = "TOGGLE_ADD_EDIT_SESSION_MODAL";
export const BEGIN_SAVE_SESSION = "BEGIN_SAVE_SESSION";
export const SAVE_SESSION_SUCCESS = "SAVE_SESSION_SUCCESS";
export const EDIT_SESSION_SUCCESS = "EDIT_SESSION_SUCCESS";
export const HANDLE_SESSION_MODAL = "HANDLE_SESSION_MODAL";
export const EDIT_SESSION_ERROR = "EDIT_SESSION_ERROR";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const SHOW_ADD_EDIT_FILM_MODAL_AT_SESSION = "SHOW_ADD_EDIT_FILM_MODAL_AT_SESSION";
export const LOAD_ALL_ROOMS_SUCCESS = "LOAD_ALL_ROOMS_SUCCESS";



export const BEGIN_LOAD_ALL_SEAT_TYPES = "BEGIN_LOAD_ALL_SEAT_TYPES";
export const LOAD_ALL_SEAT_TYPES_SUCCESS = "LOAD_ALL_SEAT_TYPES_SUCCESS";
export const TOGGLE_SEAT_TYPE_MODAL = "TOGGLE_SEAT_TYPE_MODAL";
export const HANDLE_SEAT_TYPE_MODAL = "HANDLE_SEAT_TYPE_MODAL";
export const BEGIN_SAVE_SEAT_TYPE = "BEGIN_SAVE_SEAT_TYPE";
export const EDIT_SEAT_TYPE_SUCCESS = "EDIT_SEAT_TYPE_SUCCESS";
export const EDIT_SEAT_TYPE_ERROR = "EDIT_SEAT_TYPE_ERROR";



export const TOGGLE_ADD_BOOKING_MODAL = "TOGGLE_ADD_BOOKING_MODAL";
export const BEGIN_LOAD_SEAT_BY_SESSION_ID = "BEGIN_LOAD_SEAT_BY_SESSION_ID";
export const LOAD_SEAT_BY_SESSION_ID_SUCCESS = "LOAD_SEAT_BY_SESSION_ID_SUCCESS";
export const CLEAR_SEAT_BY_SESSION_ID = "CLEAR_SEAT_BY_SESSION_ID";
export const HANDLE_BOOKING_MODAL = "HANDLE_BOOKING_MODAL";
export const BEGIN_BOOKING_SEAT = "BEGIN_BOOKING_SEAT";
export const BOOKING_SEAT_SUCCESS = "BOOKING_SEAT_SUCCESS";
export const BOOKING_SEAT_ERROR = "BOOKING_SEAT_ERROR";
export const CLEAR_ALL_BEGIN_BOOKING = "CLEAR_ALL_BEGIN_BOOKING";
export const BEGIN_CHECK_CODE = "BEGIN_CHECK_CODE";
export const CHECK_CODE_SUCCESS = 'CHECK_CODE_SUCCESS';
export const CHECK_CODE_ERROR = 'CHECK_CODE_ERROR';
export const CLEAR_CODE_BEGIN_BOOKING = 'CLEAR_CODE_BEGIN_BOOKING';
export const HANDLE_SEAT_TYPES = "HANDLE_SEAT_TYPES";




