export default {
    BEGIN_LOAD_POSTS : "BEGIN_LOAD_POSTS",
    LOADED_POSTS_SUCCESS : "LOADED_POSTS_SUCCESS",
    LOADED_POSTS_ERROR : "LOADED_POSTS_ERROR",


    BEGIN_LOAD_CATEGORIES : "BEGIN_LOAD_CATEGORIES",
    LOADED_CATEGORIES_SUCCESS : "LOADED_CATEGORIES_SUCCESS",
    LOADED_CATEGORIES_ERROR : "LOADED_CATEGORIES_ERROR",

    CHANGE_STATUS : "CHANGE_STATUS",


    OPEN_POST_MODAL : "OPEN_POST_MODAL",
    CLOSE_POST_MODAL : "CLOSE_POST_MODAL",


    BEGIN_LOAD_POST : "BEGIN_LOAD_POST",
    LOAD_POST_SUCCESS : "LOAD_POST_SUCCESS",
    LOAD_POST_ERROR : "LOAD_POST_ERROR",


    DELETE_POST_SUCCESS : "DELETE_POST_SUCCESS",


    BEGIN_LOAD_LANGUAGES : "BEGIN_LOAD_LANGUAGES",
    LOADED_LANGUAGES_SUCCESS : "LOADED_LANGUAGES_SUCCESS",
    LOADED_LANGUAGES_ERROR : "LOADED_LANGUAGES_ERROR",

    BEGIN_LOAD_FACEBOOK_STATISTIC : "BEGIN_LOAD_FACEBOOK_STATISTIC",
    LOADED_FACEBOOK_STATISTIC_SUCCESS : "LOADED_FACEBOOK_STATISTIC_SUCCESS",
    LOADED_FACEBOOK_STATISTIC_ERROR : "LOADED_FACEBOOK_STATISTIC_ERROR",


    BEGIN_UPLOAD_IMAGE : "BEGIN_UPLOAD_IMAGE",
    UPLOAD_IMAGE_SUCCESS : "UPLOAD_IMAGE_SUCCESS",
    UPLOAD_IMAGE_ERROR : "UPLOAD_IMAGE_ERROR",


    UPDATE_FORM_POST : "UPDATE_FORM_POST",


    BEGIN_SAVE_POST : "BEGIN_SAVE_POST",
    SAVE_POST_SUCCESS : "SAVE_POST_SUCCESS",
    SAVE_POST_ERROR : "SAVE_POST_ERROR",


    BEGIN_PRE_SAVE_POST : "BEGIN_PRE_SAVE_POST",
    PRE_SAVE_POST_SUCCESS : "PRE_SAVE_POST_SUCCESS",
    PRE_SAVE_POST_ERROR : "PRE_SAVE_POST_ERROR",


    BEGIN_CREATE_LANGUAGE : "BEGIN_CREATE_LANGUAGE",
    CREATE_LANGUAGE_SUCCESS : "CREATE_LANGUAGE_SUCCESS",
    CREATE_LANGUAGE_ERROR : "CREATE_LANGUAGE_ERROR",

    CLOSE_ADD_LANGUAGE_MODAL : "CLOSE_ADD_LANGUAGE_MODAL",
    OPEN_ADD_LANGUAGE_MODAL : "OPEN_ADD_LANGUAGE_MODAL",

    UPDATE_FORM_CREATE_LANGUAGE : "UPDATE_FORM_CREATE_LANGUAGE",

    OPEN_ADD_CATEGORY_MODAL : "OPEN_ADD_CATEGORY_MODAL",
    CLOSE_ADD_CATEGORY_MODAL : "CLOSE_ADD_CATEGORY_MODAL",


    BEGIN_CREATE_CATEGORY : "BEGIN_CREATE_CATEGORY",
    CREATE_CATEGORY_SUCCESS : "CREATE_CATEGORY_SUCCESS",
    CREATE_CATEGORY_ERROR : "CREATE_CATEGORY_ERROR",

    UPDATE_FORM_CREATE_CATEGORY : "UPDATE_FORM_CREATE_CATEGORY",


};
