export default {
    BEGIN_LOAD_EVENTS: "BEGIN_LOAD_EVENTS",
    LOAD_EVENTS_SUCCESS: "LOAD_EVENTS_SUCCESS",
    SHOW_STORE_EVENT_MODAL: "SHOW_STORE_EVENT_MODAL",
    UPDATE_EVENT_FORM_DATA: "UPDATE_EVENT_FORM_DATA",
    BEGIN_SAVE_EVENT: "BEGIN_SAVE_EVENT",
    SAVE_EVENT_SUCCESS: "SAVE_EVENT_SUCCESS",
    SAVE_EVENT_ERROR: "SAVE_EVENT_ERROR",
    BEGIN_LOAD_ALL_EVENTS: "BEGIN_LOAD_ALL_EVENTS",
    LOADED_ALL_EVENTS_SUCCESS: "LOADED_ALL_EVENTS_SUCCESS",
    LOADED_ALL_EVENTS_ERROR: "LOADED_ALL_EVENTS_ERROR",
    CHANGE_STATUS_IN_EVENTS: "CHANGE_STATUS_IN_EVENTS",
};
