export default {
    BEGIN_LOAD_EVENTS: "BEGIN_LOAD_EVENTS",
    LOAD_EVENTS_SUCCESS: "LOAD_EVENTS_SUCCESS",
    SHOW_STORE_EVENT_MODAL: "SHOW_STORE_EVENT_MODAL",
    UPDATE_EVENT_FORM_DATA: "UPDATE_EVENT_FORM_DATA",
};
