export const LOAD_DASHBOARD_DATA = 'LOAD_DASHBOARD_DATA';
export const BEGIN_LOAD_DASHBOARD_DATA = 'BEGIN_LOAD_DASHBOARD_DATA';

export const LOADED_COURSES_DATA = 'LOAD_COURSES_DATA';
export const BEGIN_LOAD_COURSES_DATA = 'BEGIN_LOAD_COURSES_DATA';

export const LOADED_GENS_DATA = 'LOADED_GENS_DATA';
export const BEGIN_LOAD_GENS_DATA = 'BEGIN_LOAD_GENS_DATA';

export const LOADED_SEARCH_REGISTERS_DATA = 'LOADED_SEARCH_REGISTERS_DATA';
export const BEGIN_SEARCH_REGISTERS_DATA = 'BEGIN_SEARCH_REGISTERS_DATA';

export const LOAD_REGISTER_LIST_DATA = 'LOAD_REGISTER_LIST_DATA';
export const LOAD_MORE_REGISTER_LIST_DATA = 'LOAD_MORE_REGISTER_LIST_DATA';
export const BEGIN_LOAD_REGISTER_LIST_DATA = 'BEGIN_LOAD_REGISTER_LIST_DATA';

export const BEGIN_UPDATE_LOGIN_FORM = 'BEGIN_UPDATE_LOGIN_FORM';
export const UPDATED_LOGIN_FORM = 'UPDATED_LOGIN_FORM';
export const LOGIN_ERROR = 'LOGIN_ERROR';
