export const TARGET_SALE_LOAD_GENS = "TARGET_SALE_LOAD_GENS";
export const TARGET_SALE_LOAD_GENS_SUCCESS = "TARGET_SALE_LOAD_GENS_SUCCESS";
export const TARGET_SALE_CHANGE_GEN = "TARGET_SALE_CHANGE_GEN";
export const BEGIN_TARGET_SALE_LOAD = "BEGIN_TARGET_SALE_LOAD";
export const TARGET_SALE_LOAD_SUCCESS = "TARGET_SALE_LOAD_SUCCESS";