export const BEGIN_LOAD_COURSE_CATEGORIES = 'BEGIN_LOAD_COURSE_CATEGORIES';
export const LOAD_COURSE_CATEGORIES_SUCCESS = 'LOAD_COURSE_CATEGORIES_SUCCESS';
export const TOGGLE_EDIT_CATEGORY_MODAL = "TOGGLE_EDIT_CATEGORY_MODAL";
export const HANDLE_EDIT_CATEGORY_MODAL = "HANDLE_EDIT_CATEGORY_MODAL";
export const BEGIN_SAVE_CATEGORY_MODAL = "BEGIN_SAVE_CATEGORY_MODAL";
export const SAVE_CATEGORY_SUCCESS = "SAVE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";