export default {
    BEGIN_LOAD_BASES: "BEGIN_LOAD_BASES",
    LOAD_BASES_SUCCESS: "LOAD_BASES_SUCCESS",
    LOAD_BASES_ERROR: "LOAD_BASES_ERROR",

    BEGIN_LOAD_PROVINCES: "BEGIN_LOAD_PROVINCES",
    LOAD_PROVINCES_SUCCESS: "LOAD_PROVINCES_SUCCESS",
    LOAD_PROVINCES_ERROR: "LOAD_PROVINCES_ERROR",

    BEGIN_LOAD_REGISTERS: "BEGIN_LOAD_REGISTERS",
    LOAD_REGISTERS_SUCCESS: "LOAD_REGISTERS_SUCCESS",
    LOAD_REGISTERS_ERROR: "LOAD_REGISTERS_ERROR",

    BEGIN_LOAD_SALERS: "BEGIN_LOAD_SALERS",
    LOAD_SALERS_SUCCESS: "LOAD_SALERS_SUCCESS",
    LOAD_SALERS_ERROR: "LOAD_SALERS_ERROR",


    BEGIN_SAVE_PAYMENT: "BEGIN_SAVE_PAYMENT",
    SAVED_PAYMENT_SUCCESS: "SAVED_PAYMENT_SUCCESS",
    SAVED_PAYMENT_ERROR: "SAVED_PAYMENT_ERROR",


    BEGIN_CHANGE_OFFICIAL_TIME: "BEGIN_CHANGE_OFFICIAL_TIME",
    CHANGE_OFFICIAL_TIME_SUCCESS: "CHANGE_OFFICIAL_TIME_SUCCESS",
    CHANGE_OFFICIAL_TIME_ERROR: "CHANGE_OFFICIAL_TIME_ERROR",

    OPEN_DATE_TIME_MODAL: "OPEN_DATE_TIME_MODAL",
    CLOSE_DATE_TIME_MODAL: "CLOSE_DATE_TIME_MODAL",


    OPEN_PAYMENT_MODAL: "OPEN_PAYMENT_MODAL",
    CLOSE_PAYMENT_MODAL: "CLOSE_PAYMENT_MODAL",


    OPEN_ADD_REGISTER_MODAL: "OPEN_ADD_REGISTER_MODAL",
    CLOSE_ADD_REGISTER_MODAL: "CLOSE_ADD_REGISTER_MODAL",

    OPEN_CONFIRM_MODAL: "OPEN_CONFIRM_MODAL",
    CLOSE_CONFIRM_MODAL: "CLOSE_CONFIRM_MODAL",

    UPDATE_REGISTER: "UPDATE_REGISTER",

    BEGIN_CREATE_REGISTER: "BEGIN_CREATE_REGISTER",
    CREATE_REGISTER_SUCCESS: "CREATE_REGISTER_SUCCESS",
    CREATE_REGISTER_ERROR: "CREATE_REGISTER_ERROR",

    BEGIN_LOAD_ROOMS: "BEGIN_LOAD_ROOMS",
    LOAD_ROOMS_SUCCESS: "LOAD_ROOMS_SUCCESS",
    LOAD_ROOMS_ERROR: "LOAD_ROOMS_ERROR",

    BEGIN_LOAD_BASES_BY_PROVINCE: "BEGIN_LOAD_BASES_BY_PROVINCE",
    LOAD_BASES_BY_PROVINCE_SUCCESS: "LOAD_BASES_BY_PROVINCE_SUCCESS",
    LOAD_BASES_BY_PROVINCE_ERROR: "LOAD_BASES_BY_PROVINCE_ERROR",

    BEGIN_LOAD_CAMPAIGNS: "BEGIN_LOAD_CAMPAIGNS",
    LOAD_CAMPAIGNS_SUCCESS: "LOAD_CAMPAIGNS_SUCCESS",
    LOAD_CAMPAIGNS_ERROR: "LOAD_CAMPAIGNS_ERROR",


};