export default {
    BEGIN_LOAD_BASES: "BEGIN_LOAD_BASES",
    LOAD_BASES_SUCCESS: "LOAD_BASES_SUCCESS",
    LOAD_BASES_ERROR: "LOAD_BASES_ERROR",

    BEGIN_LOAD_REGISTERS: "BEGIN_LOAD_REGISTERS",
    LOAD_REGISTERS_SUCCESS: "LOAD_REGISTERS_SUCCESS",
    LOAD_REGISTERS_ERROR: "LOAD_REGISTERS_ERROR",

    BEGIN_LOAD_SALERS: "BEGIN_LOAD_SALERS",
    LOAD_SALERS_SUCCESS: "LOAD_SALERS_SUCCESS",
    LOAD_SALERS_ERROR: "LOAD_SALERS_ERROR",

    OPEN_CALL_MODAL: "OPEN_CALL_MODAL",
    CLOSE_CALL_MODAL: "CLOSE_CALL_MODAL",

    BEGIN_CHANGE_CALL_STATUS: "BEGIN_CHANGE_CALL_STATUS",
    CHANGE_CALL_STATUS_SUCCESS: "CHANGE_CALL_STATUS_SUCCESS",
    CHANGE_CALL_STATUS_ERROR: "CHANGE_CALL_STATUS_ERROR",

    BEGIN_SAVE_PAYMENT: "BEGIN_SAVE_PAYMENT",
    SAVED_PAYMENT_SUCCESS: "SAVED_PAYMENT_SUCCESS",
    SAVED_PAYMENT_ERROR: "SAVED_PAYMENT_ERROR",
};