export const UPLOAD_ROOM_COVER_COMPLETED = "UPLOAD_ROOM_COVER_COMPLETED";
export const UPDATE_ROOM_COVER_PROGRESS = "UPDATE_ROOM_COVER_PROGRESS";
export const BEGIN_UPLOAD_ROOM_COVER = "BEGIN_UPLOAD_ROOM_COVER";
