// export const ATTENDANCE_BEGIN_LOAD_CLASS_DATA = 'ATTENDANCE_BEGIN_LOAD_CLASS_DATA';
// export const ATTENDANCE_LOAD_CLASS_DATA_SUCCESS = 'ATTENDANCE_LOAD_CLASS_DATA_SUCCESS';
// export const ATTENDANCE_LOAD_CLASS_DATA_ERROR = 'ATTENDANCE_LOAD_CLASS_DATA_ERROR';