
export const BEGIN_LOAD_SUMMARY_GOOD = "BEGIN_LOAD_SUMMARY_GOOD";
export const LOAD_SUMMARY_GOOD_SUCCESS = "LOAD_SUMMARY_GOOD_SUCCESS";
export const LOAD_SUMMARY_GOOD_ERROR = "LOAD_SUMMARY_GOOD_ERROR";

export const BEGIN_LOAD_HISTORY_GOOD = "BEGIN_LOAD_HISTORY_GOOD";
export const LOAD_HISTORY_GOOD_SUCCESS = "LOAD_HISTORY_GOOD_SUCCESS";
export const LOAD_HISTORY_GOOD_ERROR = "LOAD_HISTORY_GOOD_ERROR";
