export const TOGGLE_OPEN_MODAL = "TOGGLE_OPEN_MODAL";
export const TOGGLE_OPEN_SHOW_CODE_MODAL = "TOGGLE_OPEN_SHOW_CODE_MODAL";
export const BEGIN_SAVE_CODE = "BEGIN_SAVE_CODE";
export const SAVE_CODE_SUCCESS = "SAVE_CODE_SUCCESS";
export const HANDLE_CODE_MODAL = "HANDLE_CODE_MODAL";