export const BEGIN_LOAD_BOOKING_HISTORY = "BEGIN_LOAD_BOOKING_HISTORY";
export const LOAD_BOOKING_HISTORY_SUCCESS = "LOAD_BOOKING_HISTORY_SUCCESS";
export const BEGIN_LOAD_EXCEL_BOOKING_HISTORY = "BEGIN_LOAD_EXCEL_BOOKING_HISTORY";
export const LOAD_EXCEL_BOOKING_HISTORY_SUCCESS = "LOAD_EXCEL_BOOKING_HISTORY_SUCCESS";