export const TOGGLE_CHOOSE_SEAT_MODAL = "TOGGLE_CHOOSE_SEAT_MODAL";
export const CHOOSE_SEAT_BEGIN_LOAD_ROOMS = "CHOOSE_SEAT_BEGIN_LOAD_ROOMS";
export const CHOOSE_SEAT_LOAD_ROOMS_SUCCESS = "CHOOSE_SEAT_LOAD_ROOMS_SUCCESS";
export const CHOOSE_SEAT_SET_ACTIVE_ROOM = "CHOOSE_SEAT_SET_ACTIVE_ROOM";
export const CHOOSE_SEAT_LOAD_SEATS_SUCCESS = "CHOOSE_SEAT_LOAD_SEATS_SUCCESS";

export const CHOOSE_SEAT_BEGIN_LOAD_SEATS = "CHOOSE_SEAT_BEGIN_LOAD_SEATS";
export const TOGGLE_CONFIRM_SEAT_MODAL = "TOGGLE_CONFIRM_SEAT_MODAL";

export const CHOOSE_SEAT_SET_FROM_TIME = "CHOOSE_SEAT_SET_FROM_TIME";
export const CHOOSE_SEAT_SET_TO_TIME = "CHOOSE_SEAT_SET_TO_TIME";
